tags: [""]


general:
  debug: False
  gpus: [0]


hparams:
  model_name: "efficientnet-b3"
  model_advprop: False

  aug_pad_size: 512
  aug_border_mode: 0

  lr: 0.001
  optimizer_period: 60000

  batch_size: 32
  grad_acc: 1

  metric_period: 10

  smoothing: 0.05

  fold: 0
  

neptune:
  api_token: "HIDDEN"
  project_name: "HIDDEN"
